In [5]:
import numpy as np
j=[4,6,2,8,9]
type(j)

list

In [ ]:
LIBRARY                      FUNCTIONS

1)numpy                     array operations
2)pandas                    Datamanipulation and analysis
3)matplotlib and Seaborn    Graphical Analysis
4)sklearn                   Machine Learning Algorithms and Techniques
5)statsmodels               Statastical Analysis
6)scipy                     Statastical Analysis

In [11]:
np.array(j)  #Converts the list into an array


array([4, 6, 2, 8, 9])

In [13]:

tuple(j) #Directly coverts into tuple

(4, 6, 2, 8, 9)

In [26]:
n=[4, 8, 4, 5, 7, 5, 4]
d=np.array(n)

In [28]:
d

array([4, 8, 4, 5, 7, 5, 4])

In [30]:
d.shape

(7,)

In [32]:
d.ndim

1

In [34]:
d.size

7

In [74]:
s=[[4, 8, 3, 5, 7, 5, 4],[56,78,54,20,43,62,78],[67,98,80,49,98,78,45],[77,88,22,55,78,54,65],[90,40,70,60,88,97,64]]
s

[[4, 8, 3, 5, 7, 5, 4],
 [56, 78, 54, 20, 43, 62, 78],
 [67, 98, 80, 49, 98, 78, 45],
 [77, 88, 22, 55, 78, 54, 65],
 [90, 40, 70, 60, 88, 97, 64]]

In [76]:
type(s)

list

In [78]:
arr1=np.array(s)
arr1

array([[ 4,  8,  3,  5,  7,  5,  4],
       [56, 78, 54, 20, 43, 62, 78],
       [67, 98, 80, 49, 98, 78, 45],
       [77, 88, 22, 55, 78, 54, 65],
       [90, 40, 70, 60, 88, 97, 64]])

In [80]:
arr1.shape

(5, 7)

In [84]:
arr1.size

35

In [88]:
arr1.ndim

2

In [102]:
arr1.reshape(7, 5)

array([[ 4,  8,  3,  5,  7],
       [ 5,  4, 56, 78, 54],
       [20, 43, 62, 78, 67],
       [98, 80, 49, 98, 78],
       [45, 77, 88, 22, 55],
       [78, 54, 65, 90, 40],
       [70, 60, 88, 97, 64]])

In [104]:
 arr1.shape

(5, 7)

In [108]:
arr1.ndim

2

In [110]:
 range(5, 7)

range(5, 7)

In [112]:
m=[3,4,5,6,7,10,11,14,15]
m

[3, 4, 5, 6, 7, 10, 11, 14, 15]

In [114]:
list(range(3,13))

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [116]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [118]:
list(range(3,19,2))

[3, 5, 7, 9, 11, 13, 15, 17]

In [120]:
list(range(0,1300,100))

[0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200]

In [122]:
m=range(-10,1,1)

In [124]:
list(m)

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [126]:
list(range(-1,-10,-2))

[-1, -3, -5, -7, -9]

In [128]:
list(range(10,-10,-2))

[10, 8, 6, 4, 2, 0, -2, -4, -6, -8]

In [132]:
[8.5,6,2.3,5.6,1.0,2.0,8]

[8.5, 6, 2.3, 5.6, 1.0, 2.0, 8]

In [134]:
range(5,50,5)

range(5, 50, 5)

In [136]:
for i in range(5,50,5):
    print("Data",i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [141]:
j=[5,87,52,3,21,41,65,54,1,8]

j

[5, 87, 52, 3, 21, 41, 65, 54, 1, 8]

In [147]:

even_pos = []
odd_pos = []
j = [1, 2, 3, 4, 5]  
for i in range(len(j)):
    if i%2 == 0:
        even_pos.append(i)  
    else:
        odd_pos.append(i)
print("Even positions:", even_pos)
print("Odd positions:", odd_pos)


Even positions: [0, 2, 4]
Odd positions: [1, 3]
