In [3]:
stud_2nd=[18,19,20,20,20,19,18,18,18,20,20] 

In [9]:
import numpy as np
np.random.randint(18,21,(300))

array([19, 18, 20, 18, 20, 19, 20, 18, 18, 18, 19, 20, 20, 19, 19, 20, 19,
       20, 20, 18, 18, 20, 19, 19, 19, 20, 20, 18, 19, 20, 19, 18, 20, 19,
       19, 20, 20, 18, 18, 19, 20, 20, 19, 19, 18, 18, 20, 20, 20, 18, 18,
       18, 18, 19, 20, 19, 19, 19, 20, 19, 20, 20, 19, 20, 19, 19, 18, 19,
       20, 18, 19, 20, 19, 19, 18, 19, 20, 18, 20, 20, 20, 19, 19, 19, 18,
       18, 20, 19, 18, 19, 19, 20, 18, 18, 18, 20, 20, 18, 19, 20, 20, 18,
       20, 19, 18, 19, 18, 20, 20, 20, 18, 19, 20, 20, 18, 18, 18, 20, 20,
       20, 19, 19, 19, 20, 20, 20, 20, 19, 19, 18, 20, 20, 18, 20, 18, 20,
       18, 19, 19, 20, 19, 20, 19, 20, 19, 19, 18, 19, 20, 19, 18, 19, 18,
       19, 19, 18, 19, 18, 18, 19, 20, 20, 19, 20, 19, 18, 20, 20, 19, 19,
       20, 19, 20, 20, 20, 20, 18, 18, 18, 19, 18, 20, 20, 19, 19, 19, 18,
       19, 19, 20, 20, 18, 20, 19, 20, 18, 18, 18, 18, 19, 18, 18, 18, 18,
       19, 18, 18, 18, 18, 20, 18, 19, 18, 20, 18, 19, 18, 18, 19, 18, 20,
       18, 18, 19, 20, 19

In [15]:
np.random.seed(400)
arr=np.random.randint(18,21,(6,7))
arr

array([[18, 20, 19, 18, 20, 19, 18],
       [20, 20, 20, 19, 20, 19, 19],
       [20, 19, 20, 18, 19, 20, 20],
       [18, 18, 19, 19, 19, 18, 20],
       [20, 19, 19, 18, 18, 18, 19],
       [19, 18, 20, 18, 19, 19, 18]])

In [17]:
arr.size

42

In [31]:
m=[5,20,10,6,8]
m

[5, 20, 10, 6, 8]

In [43]:
n=[i**2 for i in m]
n

[390625, 25600000000, 100000000, 1679616, 16777216]

In [45]:
b=(3,6,7,8,9)
b

(3, 6, 7, 8, 9)

In [47]:
b=tuple(x+5 for x in b)
b

(8, 11, 12, 13, 14)

In [51]:
k=[85,25,85,75,35,45,95]
k

[85, 25, 85, 75, 35, 45, 95]

In [55]:
k=tuple(x+7 for x in k)
k

(97, 37, 97, 87, 47, 57, 107)

In [59]:
d=[]
for i in k:
    if i<50:
        d.append(i)
d

[37, 47]

In [61]:
arr

array([[18, 20, 19, 18, 20, 19, 18],
       [20, 20, 20, 19, 20, 19, 19],
       [20, 19, 20, 18, 19, 20, 20],
       [18, 18, 19, 19, 19, 18, 20],
       [20, 19, 19, 18, 18, 18, 19],
       [19, 18, 20, 18, 19, 19, 18]])

In [63]:
t=arr+2
t

array([[20, 22, 21, 20, 22, 21, 20],
       [22, 22, 22, 21, 22, 21, 21],
       [22, 21, 22, 20, 21, 22, 22],
       [20, 20, 21, 21, 21, 20, 22],
       [22, 21, 21, 20, 20, 20, 21],
       [21, 20, 22, 20, 21, 21, 20]])

In [65]:
arr**2

array([[324, 400, 361, 324, 400, 361, 324],
       [400, 400, 400, 361, 400, 361, 361],
       [400, 361, 400, 324, 361, 400, 400],
       [324, 324, 361, 361, 361, 324, 400],
       [400, 361, 361, 324, 324, 324, 361],
       [361, 324, 400, 324, 361, 361, 324]])

In [67]:
arr/2

array([[ 9. , 10. ,  9.5,  9. , 10. ,  9.5,  9. ],
       [10. , 10. , 10. ,  9.5, 10. ,  9.5,  9.5],
       [10. ,  9.5, 10. ,  9. ,  9.5, 10. , 10. ],
       [ 9. ,  9. ,  9.5,  9.5,  9.5,  9. , 10. ],
       [10. ,  9.5,  9.5,  9. ,  9. ,  9. ,  9.5],
       [ 9.5,  9. , 10. ,  9. ,  9.5,  9.5,  9. ]])