In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.random.randint(30,50,15)

In [4]:
a

array([31, 43, 42, 45, 41, 35, 34, 49, 48, 33, 32, 32, 35, 39, 47])

In [5]:
a[-2]

39

In [6]:
a[-2:-10:-1]

array([39, 35, 32, 32, 33, 48, 49, 34])

In [20]:
np.random.seed(94)
b = np.random.randint(15,50,(7,8))
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [21]:
b[2]

array([30, 41, 26, 21, 28, 29, 17, 38])

In [22]:
b[4]

array([23, 30, 25, 34, 42, 16, 39, 35])

In [23]:
b[:,7]

array([23, 18, 38, 35, 35, 47, 39])

In [24]:
b[:,3]

array([37, 25, 21, 15, 34, 45, 17])

In [25]:
b[6,4]

45

In [26]:
b[1:5]

array([[31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35]])

In [27]:
b[1:5,1:5]

array([[29, 48, 25, 47],
       [41, 26, 21, 28],
       [47, 16, 15, 48],
       [30, 25, 34, 42]])

In [28]:
b[3:7,2:7]

array([[16, 15, 48, 22, 44],
       [25, 34, 42, 16, 39],
       [21, 45, 37, 48, 23],
       [37, 17, 45, 24, 44]])

In [31]:
b[1:,1:7]

array([[29, 48, 25, 47, 39, 39],
       [41, 26, 21, 28, 29, 17],
       [47, 16, 15, 48, 22, 44],
       [30, 25, 34, 42, 16, 39],
       [45, 21, 45, 37, 48, 23],
       [37, 37, 17, 45, 24, 44]])

In [32]:
b[-6:,-7:-1]

array([[29, 48, 25, 47, 39, 39],
       [41, 26, 21, 28, 29, 17],
       [47, 16, 15, 48, 22, 44],
       [30, 25, 34, 42, 16, 39],
       [45, 21, 45, 37, 48, 23],
       [37, 37, 17, 45, 24, 44]])

In [39]:
b[2:5:2,1::3]

array([[41, 28, 38],
       [30, 42, 35]])

In [41]:
b[1:7:2,:7:2]

array([[31, 48, 47, 39],
       [49, 16, 48, 44],
       [45, 21, 37, 23]])

In [43]:
b[:4,1:7]

array([[15, 18, 37, 44, 34, 31],
       [29, 48, 25, 47, 39, 39],
       [41, 26, 21, 28, 29, 17],
       [47, 16, 15, 48, 22, 44]])